# Biblioteca NUMPY

pensa em uma das melhores e mais utilizadas bibliotecas de python, essa dai é a segunda delas, pois o pandas está em primeiro

In [2]:
# primeiro de tudo é necessário importar a biblioteca, e isso vale para todos os arquivos .py
# que voce criar ok

import numpy as np
# aqui podemos ver a nomeclatura "as" que serve pra dar um apelido pra bilioteca
# ja que qualquer comando referente ao numpy, é necessário chamar a biblioteca

In [3]:
# agora podemos começar pelo famoso começo, que é criar o seu primeiro array
# array = lista python só que com mais funções

arr_ex = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr_ex)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
# agora vc pensa qual será o tipo desse "array" criado logo acima
arr_ex = np.array([1,2,3,4,5,6,7,8,9,10])
print(type(arr_ex))

<class 'numpy.ndarray'>


In [5]:
# e assim como uma lista python, é possivel chamar elementos especificos
arr_ex = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr_ex[4])

5


In [6]:
# um extra é que da pra mencionar diversos indíces ao mesmo tempo
arr_ex = np.array([1,2,3,4,5,6,7,8,9,10])
indices = [1,2,4,6]
print(arr_ex[indices])

[2 3 5 7]


In [7]:
# ou então da pra fazer uma "máscara" encima de um array aplicando uma condição como índice
arr_ex = np.array([1,2,3,4,5,6,7,8,9,10])
mask = (arr_ex % 2 == 0)
print(arr_ex[mask])

[ 2  4  6  8 10]


In [8]:
# também é possivel substituir itens desse mesmo array com uma simples linha de código
# porém somente com números, senão voce receberá uma mensagem de erro, comprovado abaixo
arr_ex = np.array([1,2,3,4,5,6,7,8,9,10])
arr_ex[0] = 100
try:
    arr_ex[1] = 'New element'
except:
    print("Acesso Negado")
print(arr_ex)

Acesso Negado
[100   2   3   4   5   6   7   8   9  10]


In [9]:
# a não ser que seja um array ja composto originalmente de outros tipos de variável como str e bool
arr_ex = np.array([1,2,3,4,"lucca",5,6,7,True])
arr_ex[0] = "Exemplo"
print(arr_ex)

['Exemplo' '2' '3' '4' 'lucca' '5' '6' '7' 'True']


# Funções e métodos do Numpy

In [10]:
# Função CUMSUM
# ela faz com que um array se transforme nele mesmo so que a cada elemento ele vai somando o anterior com o atual
arr_ex = np.array([1,2,3,4,5,6,7,8,9,10])
arr_ex.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [11]:
# Função CUMPROD
# faz a mesma coisa do CUMSUM só que ao inves de somar os itens ele multiplica
arr_ex = np.array([1,2,3,4,5,6,7,8,9,10])
arr_ex.cumprod()

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800])

In [12]:
# Função ARANGE
# ele é igual ao RANGE do python básico
# ex: arange(começo, fim, de quantos em quantos)
arr_ex = np.arange(0,50,5)
arr_ex

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [13]:
# Função ZEROS
# ele cria um array composto somente com o numero 0 do tamanho especificado
arr_ex = np.zeros(10)
arr_ex

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
# Função EYE
# ele retorna uma matriz composta somente por 0's e 1's, sendo o 1 na diagonal principal
arr_ex = np.eye(4)
arr_ex

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
# Função DIAG
# transforma o array mencionado na diagonal principal de uma matriz composta somente por 0
arr_ex = np.diag(np.array([1,2,3,4,5]))
arr_ex

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [40]:
# Função ONES
# retorna uma matriz com o tamanho especificado de linhas e colunas
# ex: ones(num linhas, num colunas)
arr_ex = np.ones((3,4))
arr_ex

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [42]:
# Função MATRIX
# essa função transforma o array escolhido no tipo .matrix
# esse tipo de variavel é melhor pra matematica, e o array é melhor pra analise de dados
arr_ex = np.array([1,2,3,4,5,6,7,8,9,10])
arr_ex = np.matrix(arr_ex)
type(arr_ex)

numpy.matrix

In [17]:
# Função SHAPE
# essa retorna as dimensões da sua matriz
arr_ex = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
arr_ex = np.matrix(arr_ex)
np.shape(arr_ex)

(3, 3)

In [18]:
# Função SIZE
# ele retorna o numero de elementos presentes no array
arr_ex = np.array([1,2,3,4,5,6,7,8,9,10])
arr_ex.size

10

In [19]:
# Função ITEMSIZE
# ele retorna o numero de bytes necessarios para armazenar cada item no array
arr_ex = np.array([1,2,3,4,5,6,7,8,9,10])
arr_ex.itemsize

4

In [20]:
# Função NBYTES
# ele retorna o numero de bytes total que aquele array consome
arr_ex = np.array([1,2,3,4,5,6,7,8,9,10])
arr_ex.nbytes

40

In [23]:
# Função NDIM
# ele retorna o número de dimensões do array
arr_3d = np.array([[[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]],
                   [[13, 14, 15, 16],
                    [17, 18, 19, 20],
                    [21, 22, 23, 24]]])

print(arr_3d.ndim)
print(arr_3d.shape)

3
(2, 3, 4)


In [24]:
# Função MEAN
# ele retorna a média aritmética de um array
# (num1 + num2 + ... + numN) / N numeros
arr_ex = np.array([1,2,3,4,5,6,7,8,9,10])
np.mean(arr_ex)

5.5

In [25]:
# Função STD
# ele realiza o desvio padrão de um array
# (((num1 - MédiaX)² + (num2 - MediaX)² + ... + (numN - MédiaX)²) / N numeros)**0.5
arr_ex = np.array([1,2,3,4,5,6,7,8,9,10])
np.std(arr_ex)

2.8722813232690143

In [26]:
# Função VAR
# ele realiza a variância de um array
# ((num1 - MédiaX)² + (num2 - MediaX)² + ... + (numN - MédiaX)²) / N numeros
arr_ex = np.array([1,2,3,4,5,6,7,8,9,10])
np.var(arr_ex)

8.25

In [30]:
# Função DOT
# ele multiplica duas matrizes
# o número de colunas das duas matrizes tem que ser iguais
arr_ex1 = np.array([[1, 2], [3, 4]])
arr_ex2 = np.array([[5, 6], [0, 7]])

arr_result = np.dot(arr_ex1, arr_ex2)
print(arr_result)

[[ 5 20]
 [15 46]]


In [31]:
# Função ARRAY_EQUAL
# ele retorna se os dois arrays são iguais ou não com valor booleano
arr_ex1 = np.array([1, 2, 3, 4])
arr_ex2 = np.array([4, 2, 2, 4])

np.array_equal(arr_ex1,arr_ex2)

False

In [33]:
# Função MAX e MIN
# ele retorna o maior e o menor valor de um array respectivamente
arr_ex = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr_ex.min())
print(arr_ex.max())

1
10


In [37]:
# Função AROUND
# ele vai arredondar todos os valores de uma array para o inteiro mais próximo
# P.S: arredondando o 5 para baixo
arr_ex = np.array([1.2, 1.5, 1.6, 2.5, 3.5, 4.5])
print(np.around(arr_ex))

[1. 2. 2. 2. 4. 4.]


In [39]:
# Função FLATTEN
# ele faz um achatamento de matriz, transformando em uma lista com uma unica dimensão
arr_ex = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr_ex.flatten())

[1 2 3 4 5 6 7 8]


In [41]:
# Função REPEAT
# ele vai repetir cada caracter de um array o numero de vezes especificado no codigo
# ex: np.repeat(arrayX, numero de vezes repetidas)
arr_ex = np.array([1,2,3,4,5,6,7,8,9,10])
print(np.repeat(arr_ex, 3))

[ 1  1  1  2  2  2  3  3  3  4  4  4  5  5  5  6  6  6  7  7  7  8  8  8
  9  9  9 10 10 10]


In [43]:
# Função tile
# ele vai repetir a lista completa do array o numero de vezes especificado no codigo
# ex: np.tile(arrayX, numero de vezes repetidas)
arr_ex = np.array([1,2,3,4,5,6,7,8,9,10])
print(np.tile(arr_ex, 3))

[ 1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7  8  9 10  1  2  3  4
  5  6  7  8  9 10]


In [54]:
# Função DTYPE
# essa função é mais um argumento mesmo antes de terminar o codigo de criação de um array
x = np.array([1, 2])  # NumPy decide o tipo dos dado
y = np.array([1.0, 2.0])  # NumPy decide o tipo dos dado
z = np.array([1, 2], dtype = np.float64)  # Forçamos um tipo de dado em particular
print(x.dtype, y.dtype, z.dtype)

int32 float64 float64


# Indexação de Matrizes em numpy
 Para checar um valor específico em um array com varias dimensões como é o caso dos arrays em 3D, é preciso saber como chamar eles com código

In [45]:
arr_3d = dsa.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])
print(arr_3d.ndim) # Numero de dimenões (3)
print(arr_3d.shape) # Tamanho da matriz

3
(2, 3, 4)


In [46]:
# tente interpretar o array acima, pois o mesmo tem 3 dimensões
# primeiro de tudo antes de chamar um valor específico, é preciso entender como funciona o código de indexação
# voce vai colocar o nome do array (arr_3d) e depois um colchete com a cordenada necessária
arr_3d[0]
# como é possivel ver, ele chamou o primeiro termo inteiro

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
# se aplicarmos mais especificiade no código é possível chamar valores especificos
print(arr_3d[0])
print("|========|")
print(arr_3d[0,1])
print("|========|")
print(arr_3d[0,1,0])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
|========|
[5 6 7 8]
|========|
5
